function buscarf() {
	document.getElementById('buscarf').innerHTML =
	'<div class="fixed-top"><div class="input-group mb-3" style="width:100%"><div class="input-group-prepend"></div><form action="amigos.php" method="post"><input type="search" name="friends" class="form-control" placeholder="Buscar amigos..." style="background:white;border-radius:0px;border-top:none;border-right:none" autofocus></form><button onclick="qbuscarf()" class="btn btn-light" type="button" style="background:white;border:none;border-bottom:1px solid #ced4da;border-radius:0px;"><i class="fas fa-arrow-left"></i></button></div></div>';
//#ced4da
}
function qbuscarf() {
	document.getElementById('buscarf').innerHTML =
	'<nav class="navbar navbar-expand-md bg fixed-top" style="background: <?php echo $_SESSION["color"]; ?>;border: none;"><!-- Toggler/collapsibe Button --><div class="row"><div class="col-2"><button class="navbar-toggler" type="button" data-toggle="collapse" style="border: none;"><i class="fas fa-sign-out-alt"></i></button></div><div class="col-2"><button onclick="buscarf()" class="navbar-toggler" type="button" data-toggle="collapse" style="border: none;"><i class="fas fa-search"></i></button></div><div class="col-2"><button class="navbar-toggler" type="button"  data-toggle="collapse" style="border: none;"><i class="fas fa-link"></i></button></div><div class="col-2"><button class="navbar-toggler" type="button"  data-toggle="collapse" style="border: none;"><i class="fas fa-users"></i></button></div><div class="col-2"><button class="navbar-toggler" type="button"  data-toggle="collapse" style="border: none;"><i class="fas fa-bell"></i></button></div></div><!-- Navbar links --><div class="collapse navbar-collapse" id="collapsibleNavbar"><ul class="navbar-nav"><li class="nav-item asdf"><form action="../iniciar_sesion/index.php"><button type="submit" class="nav-item"><i class="fas fa-sign-in-alt"></i></button></form></li><form action="amigos.php" method="post"><input type="search" class="buscar form-control" placeholder="Buscar Amigos..." name="friends"></form><li class="nav-item asdf" style="position: fixed;right: 0;margin-right: 216px;"><form action="agregar.php"><button class="nav-item"><i class="fas fa-link"></i></button></form></li><li class="nav-item asdf" style="position: fixed;right: 0;margin-right: 163px;"><button class="nav-item"><i class="fas fa-users"></i></button></li><li class="float-right asdfs fixed-right" style="position: fixed;right: 116px;"><button class="nav-item"><i class="fas fa-bell"></i></button></li></ul></div></nav> ';
//#ced4da
}
function h() {
	document.getElementById("sexo").innerHTML = 
	'<button onclick="h()" type="button" class="btn btn-primary" style="padding-top: 15px;padding-bottom: 15px;"><center><p style="border-radius:999px;border:2px solid blue;padding-left: 5px;padding-right: 5px;width: 1px;text-align:center !important;"><i class="fas fa-male fa-2x"></i></p><center></button><button onclick="m()" type="button" class="btn btn-danger" style="padding-top: 15px;padding-bottom: 15px;"><p><i class="fas fa-female fa-2x"></i></p></button><input type="hidden" name="sexo" value="masculino"><input type="hidden" name="sexo" value="m">';
}
function m() {
	document.getElementById("sexo").innerHTML = 
	'<button onclick="h()" type="button" class="btn btn-primary" style="padding-top: 15px;padding-bottom: 15px;"><p><i class="fas fa-male fa-2x"></i></p></button><button name="m" onclick="m()" type="button" class="btn btn-danger" style="padding-top: 15px;padding-bottom: 15px;"><center><p style="border-radius:999px;border:2px solid red;padding-left: 15px;padding-right: 15px;width:29px;text-align:center !important;"><i class="fas fa-female fa-2x"></i></p></center></button><input type="hidden" value="femenino"><input type="hidden" name="sexo" value="f">';
}
